CREATE TABLE address
(
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street     VARCHAR(255) NOT NULL
);

CREATE TABLE client
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    address_id BIGINT
);

ALTER TABLE client
    ADD CONSTRAINT fk_client_on_address FOREIGN KEY (address_id) REFERENCES address (address_id);

CREATE TABLE phone
(
    phone_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number    VARCHAR(255) NOT NULL,
    client_id BIGINT
);

ALTER TABLE phone
    ADD CONSTRAINT fk_phone_on_client FOREIGN KEY (client_id) REFERENCES client (id);
